version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "card-database"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "database_postgres:/var/lib/postgresql/data"
    networks:
      - fullstack

  api:
    build: .
    container_name: "card-grpc"
    ports:
      - "50051:50051"
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_SSL_MODE=disable"
      - "DB_MIGRATION_PATH=file:///migrations"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: "bridge"